# Generated by Django 3.2.3 on 2021-05-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCategoria', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuentostr', models.CharField(max_length=50, null=True)),
                ('descuento', models.IntegerField(default=0, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMarca', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, null=True)),
                ('precio', models.IntegerField(default=0, max_length=100, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('talla', models.CharField(max_length=50, null=True)),
                ('imgProducto', models.ImageField(null=True, upload_to='imgproductos')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicpro.categoria')),
                ('descuento', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicpro.descuento')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicpro.marca')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
