# Generated by Django 3.2.3 on 2021-05-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0002_auto_20210520_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicpro.categoria'),
        ),
    ]
