# Generated by Django 3.2.3 on 2021-05-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0004_auto_20210520_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marca',
            new_name='subcategoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='subcategoria',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='NombreMarca',
            new_name='Nombresubcategoria',
        ),
    ]
