# Generated by Django 3.2.3 on 2021-05-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0006_auto_20210524_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
