# Generated by Django 3.2.3 on 2021-05-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
