# Generated by Django 3.2.3 on 2021-05-25 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicpro', '0010_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Perfil',
        ),
    ]
